version: "3.3"
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins_cicd
    ports: 
      - 50000:50000
      - 8080:8080
    volumes:
      - jenkins_home_cicd:/var/jenkins_home
volumes:
  jenkins_home_cicd:
    external: true